import jsPDF from 'jspdf';
import { FormData, GeneratedLayout, Room } from '@/types/floorPlan';

export function generateBlueprintPDF(
  formData: FormData,
  layout: GeneratedLayout
): void {
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a3',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;

  // Background
  doc.setFillColor(250, 250, 252);
  doc.rect(0, 0, pageWidth, pageHeight, 'F');

  // Title Block
  doc.setFillColor(30, 41, 59);
  doc.rect(margin, margin, pageWidth - margin * 2, 25, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('FLOOR PLAN BLUEPRINT', margin + 10, margin + 16);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated by PlanAI | ${new Date().toLocaleDateString()}`, pageWidth - margin - 10, margin + 16, { align: 'right' });

  // Plot Info Section
  const infoY = margin + 35;
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('PROJECT SPECIFICATIONS', margin, infoY);
  
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, infoY + 3, margin + 80, infoY + 3);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const specs = [
    `Plot Size: ${formData.plotLength} ft × ${formData.plotWidth} ft`,
    `Total Area: ${layout.totalArea} sq.ft`,
    `Floors: ${formData.floors}`,
    `Style: ${formData.style.charAt(0).toUpperCase() + formData.style.slice(1)}`,
    `Budget: ${formData.budgetRange.charAt(0).toUpperCase() + formData.budgetRange.slice(1)}`,
    `Vastu: ${formData.vastuCompliant ? 'Yes' : 'No'}`,
  ];
  
  specs.forEach((spec, i) => {
    doc.text(spec, margin, infoY + 12 + i * 6);
  });

  // Room Schedule
  const scheduleY = infoY + 55;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('ROOM SCHEDULE', margin, scheduleY);
  doc.line(margin, scheduleY + 3, margin + 80, scheduleY + 3);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text('Room', margin, scheduleY + 12);
  doc.text('Size (ft)', margin + 40, scheduleY + 12);
  doc.text('Area (sq.ft)', margin + 65, scheduleY + 12);

  doc.setFont('helvetica', 'normal');
  layout.rooms.forEach((room, i) => {
    const y = scheduleY + 18 + i * 5;
    if (y < scheduleY + 70) {
      doc.text(room.name, margin, y);
      doc.text(`${room.width.toFixed(1)} × ${room.height.toFixed(1)}`, margin + 40, y);
      doc.text((room.width * room.height).toFixed(1), margin + 65, y);
    }
  });

  // Floor Plan Drawing Area
  const planX = 120;
  const planY = margin + 35;
  const planWidth = pageWidth - planX - margin - 10;
  const planHeight = pageHeight - planY - margin - 30;

  // Blueprint grid background
  doc.setFillColor(240, 248, 255);
  doc.rect(planX, planY, planWidth, planHeight, 'F');

  // Grid lines
  doc.setDrawColor(200, 220, 240);
  doc.setLineWidth(0.1);
  const gridSpacing = 5;
  for (let x = planX; x <= planX + planWidth; x += gridSpacing) {
    doc.line(x, planY, x, planY + planHeight);
  }
  for (let y = planY; y <= planY + planHeight; y += gridSpacing) {
    doc.line(planX, y, planX + planWidth, y);
  }

  // Calculate scale
  const plotWidth = parseInt(formData.plotWidth) || 40;
  const plotLength = parseInt(formData.plotLength) || 60;
  const scaleX = (planWidth - 20) / plotLength;
  const scaleY = (planHeight - 20) / plotWidth;
  const scale = Math.min(scaleX, scaleY);

  const offsetX = planX + 10 + (planWidth - 20 - plotLength * scale) / 2;
  const offsetY = planY + 10 + (planHeight - 20 - plotWidth * scale) / 2;

  // Plot outline
  doc.setDrawColor(30, 41, 59);
  doc.setLineWidth(0.8);
  doc.rect(offsetX, offsetY, plotLength * scale, plotWidth * scale);

  // Draw rooms
  const roomColors: Record<string, [number, number, number]> = {
    bedroom: [230, 210, 240],
    bathroom: [210, 235, 245],
    kitchen: [255, 235, 200],
    living: [220, 235, 220],
    dining: [245, 230, 215],
    garage: [220, 220, 220],
    balcony: [200, 230, 200],
    garden: [180, 220, 180],
    hallway: [240, 240, 240],
  };

  layout.rooms.forEach((room) => {
    const rx = offsetX + room.x * scale;
    const ry = offsetY + room.y * scale;
    const rw = room.width * scale;
    const rh = room.height * scale;

    // Room fill
    const color = roomColors[room.type] || [230, 230, 230];
    doc.setFillColor(color[0], color[1], color[2]);
    doc.rect(rx, ry, rw, rh, 'F');

    // Room border
    doc.setDrawColor(80, 80, 100);
    doc.setLineWidth(0.3);
    doc.rect(rx, ry, rw, rh, 'S');

    // Room label
    doc.setFontSize(7);
    doc.setTextColor(40, 40, 60);
    doc.setFont('helvetica', 'bold');
    
    const textX = rx + rw / 2;
    const textY = ry + rh / 2;
    doc.text(room.name, textX, textY, { align: 'center' });
    
    doc.setFontSize(5);
    doc.setFont('helvetica', 'normal');
    doc.text(`${room.width.toFixed(0)}' × ${room.height.toFixed(0)}'`, textX, textY + 3, { align: 'center' });
  });

  // Dimensions
  doc.setDrawColor(100, 100, 120);
  doc.setLineWidth(0.2);
  
  // Horizontal dimension
  const dimY = offsetY - 5;
  doc.line(offsetX, dimY, offsetX + plotLength * scale, dimY);
  doc.line(offsetX, dimY - 2, offsetX, dimY + 2);
  doc.line(offsetX + plotLength * scale, dimY - 2, offsetX + plotLength * scale, dimY + 2);
  
  doc.setFontSize(8);
  doc.setTextColor(60, 60, 80);
  doc.text(`${plotLength} ft`, offsetX + (plotLength * scale) / 2, dimY - 2, { align: 'center' });

  // Vertical dimension
  const dimX = offsetX - 5;
  doc.line(dimX, offsetY, dimX, offsetY + plotWidth * scale);
  doc.line(dimX - 2, offsetY, dimX + 2, offsetY);
  doc.line(dimX - 2, offsetY + plotWidth * scale, dimX + 2, offsetY + plotWidth * scale);
  
  // Draw vertical text manually
  const verticalText = `${plotWidth} ft`;
  const textY = offsetY + (plotWidth * scale) / 2;
  doc.text(verticalText, dimX - 3, textY, { angle: 90 });

  // North Arrow
  const arrowX = planX + planWidth - 15;
  const arrowY = planY + 15;
  doc.setFillColor(30, 41, 59);
  doc.triangle(arrowX, arrowY - 8, arrowX - 4, arrowY, arrowX + 4, arrowY, 'F');
  doc.setFontSize(10);
  doc.setTextColor(30, 41, 59);
  doc.setFont('helvetica', 'bold');
  doc.text('N', arrowX, arrowY + 6, { align: 'center' });

  // Scale bar
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.text(`Scale: 1" = ${(25.4 / scale).toFixed(1)} ft`, planX + planWidth - 5, planY + planHeight + 5, { align: 'right' });

  // Efficiency rating
  doc.setFontSize(10);
  doc.setTextColor(30, 41, 59);
  doc.text(`Space Efficiency: ${(layout.efficiency * 100).toFixed(0)}%`, margin, pageHeight - margin - 5);

  // AI Suggestions
  if (layout.suggestions.length > 0) {
    const suggestY = scheduleY + 80;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text('AI RECOMMENDATIONS', margin, suggestY);
    doc.line(margin, suggestY + 2, margin + 80, suggestY + 2);
    
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    layout.suggestions.slice(0, 3).forEach((suggestion, i) => {
      doc.text(`• ${suggestion}`, margin, suggestY + 10 + i * 5);
    });
  }

  // Footer
  doc.setFillColor(30, 41, 59);
  doc.rect(margin, pageHeight - margin, pageWidth - margin * 2, 8, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(7);
  doc.text('This is a computer-generated blueprint for conceptual purposes. Consult a licensed architect for construction.', pageWidth / 2, pageHeight - margin + 5, { align: 'center' });

  // Save
  doc.save(`FloorPlan_${formData.plotLength}x${formData.plotWidth}_${Date.now()}.pdf`);
}
